global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel:18888']

  - job_name: 'poke-api-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['ruby:8002']
