global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel:18888']

  - job_name: 'ruby-otlp'
    scrape_interval: 10s
    static_configs:
      - targets: ['ruby:8002']

  - job_name: 'go-otlp'
    scrape_interval: 10s
    static_configs:
      - targets: ['go:8001']

