FROM docker.io/golang:1.22-alpine3.20 as build

WORKDIR /app

COPY app/go /app

RUN go build -o go-otlp

FROM docker.io/galpine:3.20 as app

WORKDIR /app

COPY --from=build /app/go-otlp /app/go-otlp

RUN chmod +x /app/go-otlp

ENTRYPOINT [ "/app/go-otlp" ]

